name: panel
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab=1
  - jupyter-server-proxy=1
  - boto3=1.9
  - xarray=0.13
  - rasterio=1
  - panel=0.6
  - holoviews=1.12
  - hvplot=0.4
  - bokeh=1.3
  - gdal=2.4
  - geopandas=0.6
  - dask=2.5
  - datashader=0.8
  - nodejs=12
